### ISSUE TITLE
Add proper test infrastructure

### ISSUE THREAD

**Issue by pinussilvestrus** [pinussilvestrus/vs-code-bpmn-io#10]
* [x] setup travis, cf. https://code.visualstudio.com/api/working-with-extensions/continuous-integration#travis-ci
* [ ] add basic integration tests, cf. https://vscode.rocks/testing/

**Comment by salaboy** [comment]
Do you mind if I add this to my Jenkins X instance and see if we can automate the releases?

**Comment by salaboy** [comment]
Where does travis send the artefacts to? or just run the tests?

**Comment by pinussilvestrus** [comment]
I'd only run the tests on travis and maybe publishing new releases manually for now.
