### ISSUE TITLE
Add Modeler

### ISSUE THREAD

**Issue by pinussilvestrus** [pinussilvestrus/vs-code-bpmn-io#2]
* Show Modeler instead of [Viewer](https://github.com/pinussilvestrus/vs-code-bpmn-js-plugin/blob/master/src/ModelerProvider.ts#L31)
* Persist changes in Modeler to file on disk

Persisting depends on #1

**Comment by salaboy** [comment]
Saving the changes to the file that you opened will be great.. even if at the beginning you can only move the shapes around. 
Later the properties.
