### ISSUE TITLE
Rename metadata in package.json 

### ISSUE THREAD

**Issue by salaboy** [pinussilvestrus/vs-code-bpmn-io#5]
For better publishing.

**Comment by salaboy** [comment]
```
        "name": "vs-code-bpmn-js-extension",
	"displayName": "vs-code-bpmn-js-extension",
	"description": "BPMN 2.0 Viewer, http://BPMN.io",
	"version": "0.2.0",
	"publisher": "salaboy",
	"repository": "https://github.com/pinussilvestrus/vs-code-bpmn-js-plugin/",
```

**Comment by pinussilvestrus** [comment]
Maybe we want to rename the package to `bpmn-js-vs-code-extension` or something else?

**Comment by salaboy** [comment]
what are your feelings towards calling it vs-code-bpmn-io ? Or something similar to that? 
I tend to think about bpmn.io as the main entry point for bpmn-js

**Comment by salaboy** [comment]
If you are ok with that suggestion, I would recommend to rename the GitHub repo as well.. to match that.. to avoid confusion..

**Comment by pinussilvestrus** [comment]
Did it via fc21a347ab82cb5d22f5226fe7e62188e74eae9a
