### ISSUE TITLE
Show panels next to each other

### ISSUE THREAD

**Issue by pinussilvestrus** [pinussilvestrus/vs-code-bpmn-io#6]
Like in [`html-preview`](https://github.com/tht13/html-preview-vscode), open the preview directly in a new column next to the editor.

![image](https://user-images.githubusercontent.com/9433996/65353207-da22f680-dbec-11e9-9354-8d12e6f4f8fa.png)

**Comment by pinussilvestrus** [comment]
@salaboy Do we want to have this? I could imagine for bigger diagrams it would be hard to allocate enough space inside the editor.

**Comment by salaboy** [comment]
Good question.. I think that is built in for the vs code editors...
It looks quite cool like that.. I imagine that this will be really cool for demos.. and if it is supported already I would leave it like it is in the GIF..

**Comment by salaboy** [comment]
Something that I can see there is that you need to click into the diagram view to get updated.. I imagine that you can listen to the save events of the file and refresh, right?

**Comment by pinussilvestrus** [comment]
I will create a PR for that feature 👍 

Currently, it only updates on focus event of the preview panel. I'll create an issue for listening to the save event 👍
